language: php

php:
  - 5.4
  - 5.5

before_script: 
  - yes '' | pecl install -f mongo-1.5.7
  - pear install pear/PHP_CodeSniffer
  - composer install -n
  - phpenv rehash

script: 
  - phpunit -c app
  - phpcs --standard=PSR2 --extensions=php src --ignore=adminlte
