register:
    path:     /register
    defaults: { _controller: BettingSasUserBundle:Security:register }

login:
    path:     /login
    defaults: { _controller: BettingSasUserBundle:Security:login }

login_check:
    path: /login_check
    
logout:
    path: /logout