register:
    path:     /register
    defaults: { _controller: BettingSasUserBundle:Security:register }
    methods:  [GET]

register_process:
    path:     /register
    defaults: { _controller: BettingSasUserBundle:Security:registerProcess }
    methods:  [POST]

login:
    path:     /login
    defaults: { _controller: BettingSasUserBundle:Security:login }

login_check:
    path: /login_check
    
logout:
    path: /logout
    
user_account_gambles_list:
    path: /account/gambles/list
    defaults: { _controller: BettingSasUserBundle:Gamble:listGamble }
