user_account_create_group:
    path: /user/organization/new
    defaults: { _controller: BettingSasUserBundle:Organization:new }
    methods:  [GET, POST]

user_account_select_group:
    path: /user/organization/select
    defaults: { _controller: BettingSasUserBundle:Organization:select }
    methods:  [GET, POST]

user_account_gambles_list:
    path: /user/gambles/list
    defaults: { _controller: BettingSasUserBundle:Gamble:listGamble }

user_organization_manage:
    path: /group
    defaults: { _controller: BettingSasUserBundle:Organization:manage }