parameters:
    betting_sas.organization.repository.class: BettingSas\Bundle\UserBundle\Document\Repository\OrganizationRepository
    betting_sas.organization.repository.namespace: BettingSasUserBundle:Organization
    betting_sas.user.repository.class: BettingSas\Bundle\UserBundle\Document\Repository\UserRepository
    betting_sas.user.repository.namespace: BettingSasUserBundle:User

services:
    betting_sas.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: maestro.menu.builder
        factory_method: createMenu
        arguments:
          - "@request"
          - "main"
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    betting_sas.organization.repository:
        class: %betting_sas.organization.repository.class%
        arguments:
          - %betting_sas.organization.repository.namespace%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository

    betting_sas.user.repository:
        class: %betting_sas.user.repository.class%
        arguments:
          - %betting_sas.user.repository.namespace%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository