# Event routes
event_routes:
    resource: "@BettingSasCompetitionBundle/Resources/config/routing.yml"
    
# Match routes
match_routes:
    resource: "@BettingSasSoccerWorldCupBundle/Resources/config/routing.yml"
    
# Cart routes
cart_routes:
    resource: "@BettingSasGambleBundle/Resources/config/routing.yml"
    prefix: /cart