security:
    encoders:
        BettingSas\Bundle\UserBundle\Document\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:   [ROLE_USER, ROLE_MANAGER]
        ROLE_MANAGER: [ROLE_USER]

    providers:
        main:
            mongodb:
                class: BettingSas\Bundle\UserBundle\Document\User
                property: name
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login_check
                csrf_provider: form.csrf_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/group, roles: ROLE_MANAGER }
        - { path: ^/, roles: ROLE_USER }
