parameters:
    betting_sas.menu_configuration.listener.class: BettingSas\Bundle\UIBundle\Menu\ConfigurationListener

services:
    betting_sas.menu_configuration.listener:
        class: %betting_sas.menu_configuration.listener.class%
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_listener, event: maestro.navigation.menu_configure, method: configureMenu }