BettingSas\Bundle\SoccerBundle\Document\Match:
    type: document
    fields:
        id:
            id: true
        leftTeamScore:
            type: int
            name: left_team_score
        rightTeamScore:
            type: int
            name: right_team_score
        phaseOrder:
            type: int
            name: phase_order
        phase:
            type: string
        group:
            type: string
        leftTeamAfterExtendedTimeScore:
            type: int
            name: left_team_after_extended_time_score
        rightTeamAfterExtendedTimeScore:
            type: int
            name: right_team_after_extended_time_score
        leftTeamPenaltyScore:
            type: int
            name: left_team_penalty_score
        rightTeamPenaltyScore:
            type: int
            name: right_team_penalty_score
        slug:
            index: true
            type: string
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                        - phase
                        - leftName
                        - rightName
    referenceOne:
        competition:
            targetDocument: BettingSas\Bundle\CompetitionBundle\Document\Competition