BettingSas\Bundle\SoccerBundle\Document\Match:
    type: mappedSuperclass
    fields:
        leftTeamScore:
            type: int
            name: left_team_score
        rightTeamScore:
            type: int
            name: right_team_score
        leftTeamRealScore:
            type: int
            name: left_team_real_score
        rightTeamRealScore:
            type: int
            name: right_team_real_score