BettingSas\Bundle\SoccerBundle\Document\Match:
    type: mappedSuperclass
    fields:
        left_team_score:
            type: int
        right_team_score:
            type: int
        left_team_real_score:
            type: int
        right_team_real_score:
            type: int