parameters:
    free_bet.soccer.tools.class: FreeBet\Bundle\SoccerBundle\Services\Tools
    free_bet.soccer.form.type.match.class: FreeBet\Bundle\SoccerBundle\Form\Type\MatchType

services:
    free_bet.soccer.tools:
        class: %free_bet.soccer.tools.class%

    free_bet.soccer.form.type.match:
        class: %free_bet.soccer.form.type.match.class%
        arguments:
            - @free_bet.event.repository
        tags:
            - { name: form.type, alias: match }