BettingSas\Bundle\CompetitionBundle\Document\Competition:
    type: document
    collection: competitions
    repositoryClass: BettingSas\Bundle\CompetitionBundle\Document\Repository\CompetitionRepository
    fields:
        id:
            id:  true
        name:
            type: string
            unique: true
        type:
            type: string
        slug:
            index: true
            type: string
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                        - name