BettingSas\Bundle\CompetitionBundle\Document\Event:
    type: mappedSuperClass
    collection: events
    inheritanceType: SINGLE_COLLECTION
    discriminatorField: type
    fields:
        id:
            id:  true
        leftName:
            type: string
            name: left_name
        rightName:
            type: string
            name: right_name
        processed:
            type: boolean
        date:
            type: date
        slug:
            index: true
            type: string
        created:
            type: date
            gedmo:
              timestampable:
                on: create
        updated:
            type: date
            gedmo:
              timestampable:
                on: update
    referenceOne:
        competition:
            targetDocument: BettingSas\Bundle\CompetitionBundle\Document\Competition