BettingSas\Bundle\CompetitionBundle\Document\Event:
    type: mappedSuperclass
    fields:
        id:
            id:  true
        type:
            type: string
        leftName:
            type: string
            name: left_name
        rightName:
            type: string
            name: right_name
        processed:
            type: int
        date:
            type: timestamp
        slug:
            index: true
            type: string
    referenceOne:
        competition:
            targetDocument: BettingSas\Bundle\CompetitionBundle\Document\Competition