parameters:
    betting_sas.gamble.validator.bet_type_choice.class: BettingSas\Bundle\GambleBundle\Validator\Constraints\BetTypeChoiceCoupleValidator
    betting_sas.gamble.validator.gamble_unique_type_on_event_accross_bet.class: BettingSas\Bundle\GambleBundle\Validator\Constraints\GambleUniqueTypeOnEventAccrossBetValidator

services:
    betting_sas.gamble.validator.bet_type_choice:
        class: %betting_sas.gamble.validator.bet_type_choice.class%
        arguments:
            - @betting_sas.bet_type_chain
        tags:
            - { name: validator.constraint_validator, alias: bet_type_choice }

    betting_sas.gamble.validator.gamble_unique_type_on_event_accross_bet:
        class: %betting_sas.gamble.validator.gamble_unique_type_on_event_accross_bet.class%
        arguments:
            - @betting_sas.gamble.repository
        tags:
            - { name: validator.constraint_validator, alias: gamble_unique_type_on_event_accross_bet }