parameters:
    betting_sas.twig.gamble_extension.class: BettingSas\Bundle\GambleBundle\Twig\GambleExtension
    betting_sas.gamble.cart.class: BettingSas\Bundle\GambleBundle\Component\Manager\GambleCart
    betting_sas.gamble_chain.class: BettingSas\Bundle\GambleBundle\Gamble\GambleChain

services:
    betting_sas.twig.gamble_extension:
        class: %betting_sas.twig.gamble_extension.class%
        arguments:
            - @twig
            - @betting_sas.gamble_chain
        tags:
            - { name: twig.extension }
            
    betting_sas.gamble.cart:
        class: %betting_sas.gamble.cart.class%
        arguments:
            - @doctrine_mongodb

    betting_sas.gamble_chain:
        class: "%betting_sas.gamble_chain.class%"