parameters:
    betting_sas.twig.gamble_extension.class: BettingSas\Bundle\GambleBundle\Twig\GambleExtension
    betting_sas.gamble.cart.class: BettingSas\Bundle\GambleBundle\Manager\GambleCart
    betting_sas.gamble_chain.class: BettingSas\Bundle\GambleBundle\Gamble\GambleChain
    betting_sas.gamble.cart.persister.class: BettingSas\Bundle\GambleBundle\Manager\Persister\SessionCartPersister
    betting_sas.gamble.processor.class: BettingSas\Bundle\GambleBundle\Gamble\GambleProcessor
    betting_sas.gamble.validator.class: BettingSas\Bundle\GambleBundle\Gamble\GambleValidator
    betting_sas.gamble.calculator.simple.class: BettingSas\Bundle\GambleBundle\Gamble\SimpleScoreCalculator

services:
    betting_sas.twig.gamble_extension:
        class: %betting_sas.twig.gamble_extension.class%
        arguments:
            - @twig
            - @betting_sas.gamble_chain
            - @betting_sas.gamble.cart
        tags:
            - { name: twig.extension }
            
    betting_sas.gamble.cart:
        class: %betting_sas.gamble.cart.class%
        arguments:
            - @doctrine_mongodb.odm.default_document_manager
            - @betting_sas.gamble.validator
            - @betting_sas.gamble.cart.persister

    betting_sas.gamble_chain:
        class: "%betting_sas.gamble_chain.class%"

    betting_sas.gamble.cart.persister:
        class: %betting_sas.gamble.cart.persister.class%
        arguments:
            - @session
            
    betting_sas.gamble.processor:
        class: %betting_sas.gamble.processor.class%
        arguments:
            - @betting_sas.gamble_chain
            - @betting_sas.gamble.calculator.simple

    betting_sas.gamble.calculator.simple:
        class: %betting_sas.gamble.calculator.simple.class%
        arguments:
            - @betting_sas.gamble_chain

    betting_sas.gamble.validator:
        class: %betting_sas.gamble.validator.class%
        arguments:
            - @validator
            - %betting_sas.validation_group%

    betting_sas.gamble_process.command:
        class: BettingSas\Bundle\GambleBundle\Command\ProcessGambleCommand
        arguments:
            - @doctrine_mongodb.odm.default_document_manager
            - @logger
        tags:
            - { name: console.command }
            - { name: monolog.logger, channel: gamble_process }
