BettingSas\Bundle\GambleBundle\Document\Gamble:
    properties:
        bets:
            - Count:
                min: 1
                minMessage: "A gamble must have at least one bet."

BettingSas\Bundle\GambleBundle\Document\Bet:
    properties:
        type:
            - NotBlank: ~
        choice:
            - NotBlank: ~
        event:
            - NotBlank: ~
    constraints:
        - BettingSas\Bundle\GambleBundle\Validator\Constraints\BetTypeChoiceCouple: ~