BettingSas\Bundle\UserBundle\Document\Organization:
    type: document
    collection: organizations
    fields:
        id:
            id: true
        name:
            type: string
        slug:
            index: true
            type: string
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                        - name