BettingSas\Bundle\UserBundle\Document\User:
    type: document
    collection: users
    repositoryClass: BettingSas\Bundle\UserBundle\Document\Repository\UserRepository
    fields:
        id:
            id: true
        profil:
            type: string
        slug:
            index: true
            type: string
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                        - username
    referenceOne:
        organization:
            targetDocument: BettingSas\Bundle\UserBundle\Document\Organization