event_next_list:
    path: /
    defaults: { _controller: FreeBetCompetitionBundle:Event:listNext }
    methods:  [GET]

competition_detail:
    path: /{slug}
    defaults: { _controller: FreeBetCompetitionBundle:Competition:view }
    methods:  [GET]

event_set_result:
    path: /event/{id}/edit
    defaults: { _controller: FreeBetCompetitionBundle:Event:edit }
    methods:  [GET,POST]

event_bet:
    path: /{slugCompetition}/{slugEvent}/bet
    defaults: { _controller: FreeBetCompetitionBundle:Event:bet }
    methods:  [GET]