event_next_list:
    path: /
    defaults: { _controller: BettingSasCompetitionBundle:Event:listNext }
    methods:  [GET]

competition_list:
    path: /competitions
    defaults: { _controller: BettingSasCompetitionBundle:Competition:list }
    methods:  [GET]

competition_events:
    path: /{slug}/events
    defaults: { _controller: BettingSasCompetitionBundle:Competition:listNextEvent }
    methods:  [GET]

competition_detail:
    path: /{slug}
    defaults: { _controller: BettingSasCompetitionBundle:Competition:view }
    methods:  [GET]

event_set_result:
    path: /event/{id}/edit
    defaults: { _controller: BettingSasCompetitionBundle:Event:edit }
    methods:  [GET,POST]