parameters:
    betting_sas.twig.event_extension.class: BettingSas\Bundle\CompetitionBundle\Twig\EventExtension
    betting_sas.twig.string_extension.class: BettingSas\Bundle\CompetitionBundle\Twig\StringExtension
    betting_sas.competition.repository.class: BettingSas\Bundle\CompetitionBundle\Document\Repository\CompetitionRepository
    betting_sas.competition.repository.namespace: BettingSasCompetitionBundle:Competition
    betting_sas.event.repository.class: BettingSas\Bundle\CompetitionBundle\Document\Repository\EventRepository
    betting_sas.event.repository.namespace: BettingSasCompetitionBundle:Event

services:
    betting_sas.event_inheritance.listener:
        class: BettingSas\Bundle\CompetitionBundle\Document\EventListener\EventInheritanceListener
        arguments:
            - %betting_sas.event_mapping%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: loadClassMetadata }

    betting_sas.competition.repository:
        class: %betting_sas.competition.repository.class%
        arguments:
          - %betting_sas.competition.repository.namespace%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository

    betting_sas.event.repository:
        class: %betting_sas.event.repository.class%
        arguments:
          - %betting_sas.event.repository.namespace%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository

    sensio_framework_extra.converter.doctrine.odm:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
            - { name: request.param_converter }

    betting_sas.twig.event_extension:
        class: %betting_sas.twig.event_extension.class%
        arguments:
            - @twig
        tags:
            - { name: twig.extension }

    betting_sas.twig.string_extension:
        class: %betting_sas.twig.string_extension.class%
        tags:
            - { name: twig.extension }