parameters:
    betting_sas.competition.manager.class: BettingSas\Bundle\CompetitionBundle\Manager\CompetitionManager
    betting_sas.event_form_type_guesser_chain.class: BettingSas\Bundle\CompetitionBundle\Form\Guesser\EventFormTypeGuesser

services:
    betting_sas.event_inheritance.listener:
        class: BettingSas\Bundle\CompetitionBundle\Document\EventListener\EventInheritanceListener
        arguments:
            - %betting_sas.event_mapping%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: loadClassMetadata }

    betting_sas.competition.manager:
        class: %betting_sas.competition.manager.class%
        arguments:
            - @doctrine_mongodb
            - %betting_sas.event_mapping%

    betting_sas.event_form_type_guesser_chain:
        class: "%betting_sas.event_form_type_guesser_chain.class%"

    sensio_framework_extra.converter.doctrine.odm:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
            - { name: request.param_converter }