BettingSas\Bundle\GambleBundle\Document\Bet:
    type: embeddedDocument
    fields:
        type:
            type: string
        choice:
            type: string
    referenceOne:
        event:
            targetDocument: BettingSas\Bundle\CompetitionBundle\Document\Event