BettingSas\Bundle\GambleBundle\Document\Gamble:
    type: document
    collection: gambles
    repositoryClass: BettingSas\Bundle\GambleBundle\Document\Repository\GambleRepository
    fields:
        id:
            id: true
        winner:
            type: boolean
        point:
            type: int
        processedDate:
            type: date
        created:
            type: date
            gedmo:
              timestampable:
                on: create
        updated:
            type: date
            gedmo:
              timestampable:
                on: update
    referenceOne:
        user:
            targetDocument: BettingSas\Bundle\UserBundle\Document\User
        organization:
            targetDocument: BettingSas\Bundle\UserBundle\Document\Organization
    embedMany:
        bets:
            targetDocument: BettingSas\Bundle\GambleBundle\Document\Bet