BettingSas\Bundle\GambleBundle\Document\Gamble:
    type: document
    collection: gambles
    fields:
        id:
            id: true
        winner:
            type: boolean
        point:
            type: int
        processedDate:
            type: date
        created:
            type: date
            gedmo:
              timestampable:
                on: create
        updated:
            type: date
            gedmo:
              timestampable:
                on: update
    embedMany:
        bets:
            targetDocument: BettingSas\Bundle\GambleBundle\Document\Bet