parameters:
    betting_sas.gamble.soccer.winner.class: BettingSas\Bundle\SoccerBundle\BetType\WinnerGamble
    betting_sas.gamble.soccer.exact_score.class: BettingSas\Bundle\SoccerBundle\BetType\ExactScoreGamble

services:
    betting_sas.gamble.soccer.winner:
        class: %betting_sas.gamble.soccer.winner.class%
        calls:
             - [setTranslator, ["@translator"]]
        tags:
            -  { name: betting_sas.bet_type, type: soccer, order: 1 }

    betting_sas.gamble.soccer.exact_score:
        class: %betting_sas.gamble.soccer.exact_score.class%
        tags:
            -  { name: betting_sas.bet_type, type: soccer, order: 10 }