parameters:
    betting_sas.gamble.soccer.winner.class: BettingSas\Bundle\SoccerBundle\Gamble\WinnerGamble
    betting_sas.gamble.soccer.exact_score.class: BettingSas\Bundle\SoccerBundle\Gamble\ExactScoreGamble

services:
    betting_sas.gamble.soccer.winner:
        class: %betting_sas.gamble.soccer.winner.class%
        tags:
            -  { name: betting_sas.gamble, type: soccer, order: 1 }

    betting_sas.gamble.soccer.exact_score:
        class: %betting_sas.gamble.soccer.exact_score.class%
        tags:
            -  { name: betting_sas.gamble, type: soccer, order: 10 }