parameters:
    betting_sas.soccer.tools.class: BettingSas\Bundle\SoccerBundle\Services\Tools
    betting_sas.soccer.form.type.match.class: BettingSas\Bundle\SoccerBundle\Form\Type\MatchType

services:
    betting_sas.soccer.tools:
        class: %betting_sas.soccer.tools.class%

    betting_sas.soccer.form.type.match:
        class: %betting_sas.soccer.form.type.match.class%
        tags:
            - { name: form.type, alias: match }